### ISSUE TITLE
eslint_d throws Error: Invalid option '--color' when '--color' is not even used

### ISSUE THREAD

**Issue by CxRes** [roadhump/SublimeLinter-contrib-eslint_d#10]
I am getting the following error message:

```
SublimeLinter: chdir not set or invalid, using D:\Users\X\dev\syn3\src 
SublimeLinter: eslint_d: config.js ['C:\\Program Files\\npm\\eslint_d.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__', '--config', 'D:\\Users\\X\\dev\\syn3\\.eslintrc'] 
SublimeLinter: eslint_d output:
Error: Invalid option '--color' - perhaps you meant '--ignore'? 
```

I do not understand the cause as `--color` is not even used
on Node v5.5, Windows 10 x64, eslint_d 3.1.0

**Comment by matanh-tzmedical** [comment]
+1

**Comment by roadhump** [comment]
Can you run eslint_d in console and check if it is an issue of eslint_d itself?

**Comment by matanh-tzmedical** [comment]
This seems to have fixed itself on my system somehow. Not sure what caused it. Can anyone else confirm?

**Comment by roadhump** [comment]
I suppose it was a bug of eslint_d itself and it was fixed with new version.

**Comment by jefe-spain** [comment]
I've got the same problem, I'm using the latest version of the plugin and the latest version of SublimeLinter, but still got the same error and I don't know why:

`SublimeLinter: eslint_d: gutter.js ['/Users/jfernandez/.npm-packages/bin/eslint_d', '--format', 'compact', '--stdin', '--stdin-filename', '__RELATIVE_TO_FOLDER__', '--config', '/Users/jfernandez/projects/gutter-skins/.eslintrc'] 
SublimeLinter: eslint_d output:
Error: Invalid option '--color' - perhaps you meant '--ignore'?``

eslint_d runs correctly in console.

Node 5.6.0, eslint_d 3.1.0, OSX. 

Thanks!

**Comment by roadhump** [comment]
Can't reproduce. Probably you should update your local eslint installation too?

**Comment by jefe-spain** [comment]
It's the eslint_d version, works under v2.20 , not v3.1.0

**Comment by xedef** [comment]
+1
Tried with Node 5.9.1 and 0.12.7
Tried with eslint_d 3.1.0, 2.5.1, 2.4.0 and 2.2.0.
Removed and reinstalled all SublimeLinter and SublimeLinter-contrib-eslint_d packages.
Still happening.
